CREATE TYPE user_role_enum AS ENUM ('admin', 'merchant');

CREATE TABLE users
(
    id            int8 primary key generated by default as identity,
    email         varchar(255)             not null,
    password_hash varchar(255)             not null,
    first_name    varchar(255)             not null,
    last_name     varchar(255)             not null,
    role          user_role_enum           not null default 'merchant',
    created_at    timestamp with time zone not null default now(),
    updated_at    timestamp with time zone not null default now(),
    deleted_at    timestamp with time zone
);

CREATE TABLE customers
(
    id          int8 primary key generated by default as identity,
    email       varchar(255)             not null,
    first_name  varchar(255)             not null,
    last_name   varchar(255)             not null,
    created_at  timestamp with time zone not null default now(),
    updated_at  timestamp with time zone not null default now(),
    deleted_at  timestamp with time zone,
    has_account boolean                  not null default false
);

CREATE TABLE images
(
    id         int8 primary key generated by default as identity,
    url        varchar(255),
    created_at timestamp with time zone not null default now(),
    is_main    boolean                  not null default false,
    updated_at timestamp with time zone not null default now(),
    deleted_at timestamp with time zone
);

CREATE TABLE currencies
(
    code   varchar(3) primary key,
    name   varchar(255),
    symbol varchar(255)
);

CREATE TABLE categories
(
    id         int8 primary key generated by default as identity,
    name       varchar(255)             not null,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    deleted_at timestamp with time zone
);

CREATE TABLE collections
(
    id         int8 primary key generated by default as identity,
    title      varchar(255)             not null,
    handle     varchar(255)             not null,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    deleted_at timestamp with time zone
);

CREATE TABLE products
(
    id              int8 primary key generated by default as identity,
    title           varchar(255) not null,
    subtitle        varchar(255),
    description     text,
    handle          varchar(255) not null,
    brand           varchar(255),
    condition       varchar(255),
    material        varchar(255),
    is_published    boolean      not null default false,
    model           text,
    collection_id   int8
        constraint fk_products_collections references collections,
    production_note text
);


CREATE TABLE products_categories
(
    product_id  int8
        constraint fk_products_categories_products references products,
    category_id int8
        constraint fk_products_categories_categories references categories,
    primary key (product_id, category_id)
);

CREATE TABLE product_images
(
    product_id int8
        constraint fk_product_images_products references products,
    image_id   int8
        constraint fk_product_images_images references images,
    primary key (product_id, image_id)
);

CREATE TABLE product_prices
(
    id          int8 primary key generated by default as identity,
    variant_id  int8
        constraint fk_product_prices_variants references product_variants,
    currency_id varchar(3)
        constraint fk_product_prices_currencies references currencies,
    price       int4                     not null,
    created_at  timestamp with time zone not null default now(),
    updated_at  timestamp with time zone not null default now(),
    deleted_at  timestamp with time zone,
    UNIQUE (variant_id, currency_id)
);

CREATE TABLE addresses
(
    id          int8 primary key generated by default as identity,
    customer_id int8
        constraint fk_addresses_customers references customers,
    first_name  varchar(255),
    last_name   varchar(255),
    address     varchar(255),
    city        varchar(255),
    province    varchar(255),
    country     varchar(255),
    zip         varchar(255),
    phone       varchar(255),
    created_at  timestamp with time zone not null default now(),
    updated_at  timestamp with time zone not null default now(),
    deleted_at  timestamp with time zone
);

CREATE TYPE discount_type_enum AS ENUM ('percentage', 'fixed', 'free_shipping');

CREATE TABLE promotions
(
    id          int8 primary key generated by default as identity,
    code        varchar(255)             not null,
    is_active   boolean                  not null default false,
    type        discount_type_enum       not null,
    usage_limit int4                     not null default 1,
    ends_at     timestamp with time zone not null,
    created_at  timestamp with time zone not null default now(),
    updated_at  timestamp with time zone not null default now(),
    deleted_at  timestamp with time zone
);

CREATE TABLE payment_providers
(
    id         int8 primary key generated by default as identity,
    name       varchar(255)             not null,
    enabled    boolean                  not null default false,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    deleted_at timestamp with time zone
);

CREATE TYPE order_status_enum AS ENUM ('pending', 'processing', 'shipped', 'delivered', 'cancelled');
CREATE TYPE payment_status_enum AS ENUM ('pending', 'confirmed', 'refunded');


CREATE TABLE shipping_methods
(
    id            int8 primary key generated by default as identity,
    name          varchar(255)             not null,
    description   text,
    cost          decimal(10, 2)           not null,
    delivery_time varchar(255),
    created_at    timestamp with time zone not null default now(),
    updated_at    timestamp with time zone not null default now()
);

CREATE SEQUENCE order_number_seq;

CREATE TABLE orders
(
    id                 int8 primary key generated by default as identity,
    customer_id        int8
        constraint fk_orders_customers references customers,
    address_id         int8
        constraint fk_orders_addresses references addresses,
    promotion_id       int8
        constraint fk_orders_promotions references promotions,
    status             order_status_enum        not null default 'pending',
    payment_status     payment_status_enum      not null default 'pending',
    total_price        int4                     not null,
    created_at         timestamp with time zone not null default now(),
    updated_at         timestamp with time zone not null default now(),
    deleted_at         timestamp with time zone,
    shipping_method_id int8
        constraint fk_orders_shipping_methods references shipping_methods,
    order_number       varchar(255) unique      not null default (nextval('order_number_seq')::text)
);

CREATE TABLE payments
(
    id                  int8 primary key generated by default as identity,
    order_id            int8
        constraint fk_payments_orders references orders,
    payment_provider_id int8
        constraint fk_payments_payment_providers references payment_providers,
    status              payment_status_enum      not null default 'pending',
    amount              int4                     not null,
    created_at          timestamp with time zone not null default now(),
    updated_at          timestamp with time zone not null default now(),
    deleted_at          timestamp with time zone
);

CREATE TABLE order_items
(
    id         int8 primary key generated by default as identity,
    order_id   int8
        constraint fk_order_items_orders references orders,
    product_id int8
        constraint fk_order_items_products references products,
    quantity   int4                     not null,
    price      int4                     not null,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    deleted_at timestamp with time zone
);

CREATE TYPE product_variant_enum AS ENUM ('size', 'color');

CREATE TABLE product_variants
(
    id            int8 primary key generated by default as identity,
    product_id    int8                     not null
        CONSTRAINT fk_product_variants_products REFERENCES products,
    variant_name  product_variant_enum     not null,
    variant_value varchar(255)             not null,
    sku           varchar(255),
    inventory     int4,
    created_at    timestamp with time zone not null default now(),
    updated_at    timestamp with time zone not null default now(),
    UNIQUE (product_id, sku)
);

create table notification
(
    id            varchar                                not null
        constraint notification_pkey
            primary key,
    event_name    varchar,
    resource_type varchar                                not null,
    resource_id   varchar                                not null,
    customer_id   varchar
        constraint notification_customer_id_fk
            references customers,
    "to"          varchar,
    data          jsonb                                  not null,
    provider_id   varchar
        constraint notification_provider_id_fk
            references payment_providers,
    created_at    timestamp with time zone default now() not null,
    updated_at    timestamp with time zone default now() not null
);

create index "idx_notification_resource_type"
    on notification (resource_type);

create index "idx_notification_resource_id"
    on notification (resource_id);

create index "idx_notification_customer_id"
    on notification (customer_id);
