basePath: /
definitions:
  CreateUser:
    properties:
      email:
        type: string
      full_name:
        type: string
      password:
        type: string
    required:
      - email
      - full_name
      - password
    type: object
  User:
    properties:
      created_at:
        type: string
      email:
        type: string
      full_name:
        type: string
      id:
        type: integer
      updated_at:
        type: string
    type: object
host: localhost:8080
info:
  contact: { }
  description: This is a sample server ClanPlatform server.
  title: ClanPlatform API
  version: "1.0"
paths:
  /admin/users:
    get:
      consumes:
        - application/json
      description: get users
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/User'
            type: array
      summary: List users
      tags:
        - users
    post:
      consumes:
        - application/json
      description: create user
      parameters:
        - description: User data
          in: body
          name: user
          required: true
          schema:
            $ref: '#/definitions/CreateUser'
      produces:
        - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/User'
      summary: Create user
      tags:
        - users
swagger: "2.0"
